### ISSUE TITLE
[BUG] Exception in plugin Jpa Support(2.0.3)

### ISSUE THREAD

**Issue by ZhaoxiongTan** [carter-ya/idea-plugin-jpa-support#68]
**Describe the bug （描述这个Bug）**
idea ce 启动时, 提示jpa插件异常

**Expected behavior （期望的行为）**

**Screenshots （截图，如果有的话）**

**idea version (idea的版本号):**
IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Non-Bundled Plugins: Gradle View, Lombook Plugin, zielu.svntoolbox, com.ifengxue.plugin.jpa-support, net.vektah.codeglance, zielu.gittoolbox, Docker, org.jetbrains.kotlin

**idea plugin jpa support version (idea plugin jpa support的版本号）:**
2.0.3

异常日志:
Following exceptions happened soon after this one, most probably they are induced.

2020-08-25T13:06:11.059
com.intellij.diagnostic.PluginException: com/intellij/database/model/DasObject [Plugin: com.ifengxue.plugin.jpa-support]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:223)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:549)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:537)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.actionSystem.ActionGroupStub.initGroup(ActionGroupStub.kt:32)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:253)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:549)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:537)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1551)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/database/model/DasObject
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:212)
	... 30 more
Caused by: java.lang.ClassNotFoundException: com.intellij.database.model.DasObject PluginClassLoader[PluginDescriptor(name=Jpa Support, id=com.ifengxue.plugin.jpa-support, path=C:\Users\tanzx\AppData\Roaming\JetBrains\IdeaIC2020.2\plugins\Jpa Support, version=2.0.3)] com.intellij.ide.plugins.cl.PluginClassLoader@6b6073bd
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 33 more

**Comment by carter-ya** [comment]
问题已收到，我复现下

**Comment by carter-ya** [comment]
@ZhaoxiongTan  请下载该版本来修复问题 [Jpa.Support-2.0.3.1.zip](https://github.com/carter-ya/idea-plugin-jpa-support/releases/download/v2.0.3.1/Jpa.Support-2.0.3.1.zip)

**Comment by ZhaoxiongTan** [comment]
> @ZhaoxiongTan 请下载该版本来修复问题 [Jpa.Support-2.0.3.1.zip](https://github.com/carter-ya/idea-plugin-jpa-support/releases/download/v2.0.3.1/Jpa.Support-2.0.3.1.zip)

没问题啦
