### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zwxx960** [carter-ya/idea-plugin-jpa-support#94]
java.lang.NullPointerException

at com.ifengxue.plugin.util.ColumnUtil.parseColumn(ColumnUtil.java:45)

at com.ifengxue.plugin.util.ColumnUtil.columnSchemaToColumn(ColumnUtil.java:35)

at com.ifengxue.plugin.gui.SelectTablesDialog.findColumns(SelectTablesDialog.java:211)

at com.ifengxue.plugin.gui.SelectTablesDialog.access$000(SelectTablesDialog.java:89)

at com.ifengxue.plugin.gui.SelectTablesDialog$GeneratorRunner.run(SelectTablesDialog.java:312)

at com.ifengxue.plugin.gui.SelectTablesDialog.lambda$new$7(SelectTablesDialog.java:193)

at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)

at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)

at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)

at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)

at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)

at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)

at java.desktop/java.awt.Component.processEvent(Component.java:6400)

at java.desktop/java.awt.Container.processEvent(Container.java:2263)

at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)

at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)

at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)

at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)

at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)

at java.desktop/java.awt.Dialog.show(Dialog.java:1070)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)

at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)

at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)

at com.ifengxue.plugin.gui.SelectTablesDialog.show(SelectTablesDialog.java:243)

at com.ifengxue.plugin.gui.AutoGeneratorSettingsDialog.lambda$doOKAction$6(AutoGeneratorSettingsDialog.java:212)

at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)

at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)

at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)

at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)

at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)

at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)

at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)

at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)

at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)

at java.desktop/java.awt.Dialog.show(Dialog.java:1070)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)

at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)

at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)

at com.ifengxue.plugin.gui.AutoGeneratorSettingsDialog.show(AutoGeneratorSettingsDialog.java:257)

at com.ifengxue.plugin.gui.DatabaseSettingsDialog.lambda$doOKAction$5(DatabaseSettingsDialog.java:203)

at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)

at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)

at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)

at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)

at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)

at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)

at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)

at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)

at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)

at java.desktop/java.awt.Dialog.show(Dialog.java:1070)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)

at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)

at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)

at com.ifengxue.plugin.gui.DatabaseSettingsDialog.showDialog(DatabaseSettingsDialog.java:257)

at com.ifengxue.plugin.action.JpaSupport.actionPerformed(JpaSupport.java:12)

at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)

at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)

at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)

at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)

at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)

at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514)

at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)

at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)

at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)

at java.desktop/java.awt.Component.processEvent(Component.java:6400)

at java.desktop/java.awt.Container.processEvent(Container.java:2263)

at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)

at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)

at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)

at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)

at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by carter-ya** [comment]
IDEA Version?
Plugin Version?
Database vendor?Mysql、PG、Oracle, etc...

**Comment by zwxx960** [comment]
IntelliJ IDEA 2020.3.1 (Community Edition)

Build #IC-203.6682.168, built on December 29, 2020


2.0.7-RC1

sqlserver

**Comment by carter-ya** [comment]
[Jpa Support.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/6181584/Jpa.Support.zip)
This may be caused b comment value is `null`, You try to use this version.

**Comment by zwxx960** [comment]
Because of work environment network restriction, I can't use jar downloaded from github, could you please release a new version on idea plugin website?

**Comment by carter-ya** [comment]
You can download from [Jetbrains](https://plugins.jetbrains.com/plugin/10707-jpa-support/versions/RC/114536)

**Comment by zwxx960** [comment]
it worked! thank you~
